version: '3.8'

services:
  samba:
    image: pengshp/samba
    container_name: samba4
    command: '-u "1000:1000:pirate:pirate:pw" -s "SmbShare:/share:rw:pirate"'
    # command: '-u "uid:guid:username:groupname:put-any-password-here" -s "SmbShare:/share:rw:username"'
    environment:
      TZ: 'Asia/Shanghai'
    ports:
      - "445:445/tcp"
    volumes:
    - ${pwd}/data/:/share
    #- /path/to/be/shared:/share
    restart: on-failure
    
    