version: '3.8'

services:
  samba:
    image: pengshp/samba
    container_name: samba4
    command: '-u "1000:1000:share:share:pw" -s "SmbShare:/share:rw:share"'
    # command: '-u "uid:guid:username:groupname:password" -s "SmbShare:/share:rw:username"'
    environment:
      TZ: 'Asia/Shanghai'
    network_mode: host
    volumes:
    - ${pwd}/data/:/share
    restart: on-failure